apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: bookapp-pipeline
  namespace: default
spec:
  params:
    - name: GIT_REPO
    - name: IMAGE
  workspaces:
    - name: shared-workspace
    - name: dockerconfig
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.GIT_REPO)
    - name: build-and-push
      runAfter: [clone]
      taskRef:
        name: docker-build-and-push
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: DOCKERFILE
          value: ./Dockerfile

